# Generated by Django 3.1.3 on 2020-11-11 01:44

import core.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cpf', core.models.CPFField(max_length=11, null=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Endereço de e-mail')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Função')),
                ('is_active', models.BooleanField(default=True, verbose_name='Perfil Ativo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'permissions': (('admin_user', 'Can Admin Usuários'), ('disable_user', 'Can disable Usuário')),
            },
        ),
    ]
