# Generated by Django 3.1.3 on 2020-11-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alertconfig_electricalnetwork_rails_station'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertconfig',
            options={'verbose_name': 'Config. Alerta'},
        ),
        migrations.AlterField(
            model_name='line',
            name='humanized_name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Nome Humanizado'),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Nome'),
        ),
    ]
