# Generated by Django 3.1.3 on 2020-11-22 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201120_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='Encerrado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.line', verbose_name='Linha')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Ocorrência',
            },
        ),
    ]
