# Generated by Django 3.1.3 on 2020-11-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalnetwork',
            name='km',
            field=models.PositiveIntegerField(null=True, verbose_name='KM'),
        ),
        migrations.AddField(
            model_name='electricalnetwork',
            name='pole',
            field=models.CharField(max_length=5, null=True, verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='electricalnetwork',
            name='side_power_supply',
            field=models.CharField(max_length=5, null=True, verbose_name='Alimentação Lado'),
        ),
        migrations.AlterField(
            model_name='electricalnetwork',
            name='temperature',
            field=models.FloatField(null=True, verbose_name='Temperatura'),
        ),
    ]
