# Generated by Django 3.1.3 on 2020-11-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201124_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalnetwork',
            name='image',
            field=models.CharField(max_length=1000, null=True, verbose_name='Imagem'),
        ),
    ]
